/*
RECOLECCION >
    MINERIA
    HERBORISTERIA
    PELETERIA
    PESCA

EQUIPO >
        ARMAS
        ARMADURAS
        JOYAS
ATRIBUTOS
        COMIDA
        ALQUIMIA

NOTAS:
    ORIGEN>
        Recolección 
        Monstruos
        Misiones
        Comercio con NPCs o jugadores.
    FUNCION>
        PRODUCTO FINAL
        COMPONENTE
        PRODUCTO COMERCIAL (MEJORAS BASE O GREMIO?: CAÑONES PARA BARCO X10)
    RECETAS>
        RANGOS > DESBLOQUEAR NUEVAS RECETAS
        MASTERIÍA > REINICIAR RANGO CON BONO A LOS RESULTADOS
        TIEMPO > DURACION CRAFTEO / COOLDOWN 
        MEJORAS > RECETAS MEJORADAS CON MAS COMPONENTES?
    MISIONES>
*/